name: Check Test Coverage
on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node_version: 20
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate coverage report
        run: yarn json-coverage
      - name: Generate coverage percentage
        run: echo "COV=$(yarn --silent coverage)" >> $GITHUB_ENV
      - name: Check the coverage value
        run: echo "$COV"
      